name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('requirements.txt') }}    
    - name: Install system dependencies
      run: |
        sudo apt-get -y install libzbar0 poppler-utils pkg-config libxml2-dev libxmlsec1-dev libxmlsec1-openssl
    - name: Install python dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install pytest
    - name: Setup config
      run: |
        cp instance/config_example.toml instance/config.toml
    - name: Testing the code with pytest
      run: |
        python -m pytest

  deploy:
    needs: test
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: deploy on production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        proxy_host: ${{secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_passphrase: ${{ secrets.PROXY_PASSPHRASE }}
        proxy_key: ${{ secrets.PROXY_KEY }}
        proxy_port: ${{ secrets.PROXY_PORT }}
        script_stop: true
        script: |
          cd space-trace
          git pull
          sudo systemctl restart space-trace
